version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/go.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5001:5001"
    restart: always
    tty: true
    environment:
      ENV: dev
      PORT: 5001
    env_file:
      - .env
    command: sh ./scripts/api.sh
